/**
 * generate-version.mjs
 *
 * Writes `src/version.ts` from the current `package.json` version so the
 * SDK never drifts from the published artifact. Runs as part of the
 * `prebuild` script and is committed to the repo for a clean checkout
 * + typecheck experience.
 *
 * Run:  node scripts/generate-version.mjs
 * Auto: runs before every `tsup` build via the `prebuild` script.
 */
import { readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(__dirname, '..', 'package.json');
const outPath = join(__dirname, '..', 'src', 'version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));

const banner = `// AUTO-GENERATED - do not edit by hand.
// Source: package.json @ "version" (regenerated by scripts/generate-version.mjs).
`;

const contents = `${banner}
export const SDK_VERSION = '${pkg.version}';
export const SDK_NAME = 'babysea-node';
`;

writeFileSync(outPath, contents);

console.log(`generate-version: wrote ${outPath} (v${pkg.version})`);
