// AUTO-GENERATED - do not edit by hand.
// Source: package.json @ "version" (regenerated by scripts/generate-version.mjs).

export const SDK_VERSION = '2.0.0';
export const SDK_NAME = 'babysea-node';
